/**
 * @file ValidatePage.jsx
 * @description Principal certificate validation and approval page for Cervify.
 *
 * After an administrator generates certificate numbers for an activity, the
 * Principal reviews and formally approves (validates) them here.
 *
 * Workflow:
 *  1. Principal selects an activity from the dropdown.
 *  2. The page shows all participants with their assigned certificate numbers and status.
 *  3. Principal clicks "Approve All" → POST /api/certificates/validate { approve: true }
 *  4. Principal can also "Revoke Approval" → POST /api/certificates/validate { approve: false }
 *
 * Certificate status:
 *  1 → Generated (pending validation)
 *  2 → Validated/Approved by Principal
 */

import React, { useState } from 'react';
import { CheckSquare, Check, X } from 'lucide-react';
import { useAppContext } from '../../context/AppContext';
import { certificateApi, participantApi } from '../../api/api';

/** @returns {JSX.Element} */
export default function ValidatePage() {
    const { token, activities, refreshData } = useAppContext();

    const [actId,      setActId]      = useState('');
    const [certs,      setCerts]      = useState([]);
    const [isLoading,  setIsLoading]  = useState(false);
    const [statusMsg,  setStatusMsg]  = useState('');
    const [errorMsg,   setErrorMsg]   = useState('');

    const notify = (msg, isError = false) => {
        if (isError) { setErrorMsg(msg); setTimeout(() => setErrorMsg(''), 5000); }
        else         { setStatusMsg(msg); setTimeout(() => setStatusMsg(''), 5000); }
    };

    // ── Load participant/cert data for selected activity ──────────────────────
    const loadCerts = async (id) => {
        setActId(id);
        setCerts([]);
        if (!id) return;
        setIsLoading(true);
        try {
            const data = await participantApi.get(token, id);
            setCerts(data.participants.filter(p => p.certificate_id !== null));
        } catch (err) { notify(err.message, true); }
        finally { setIsLoading(false); }
    };

    // ── Approve / Revoke ──────────────────────────────────────────────────────
    const handleValidate = async (approve) => {
        if (!actId) return notify('Please select an activity.', true);
        const action = approve ? 'approve' : 'revoke';
        if (!window.confirm(`Are you sure you want to ${action} all certificates for this activity?`)) return;
        try {
            const result = await certificateApi.validate(token, Number(actId), approve);
            await loadCerts(actId);
            await refreshData();
            notify(result.message);
        } catch (err) { notify(err.message, true); }
    };

    const allValidated = certs.length > 0 && certs.every(c => c.cert_status === 2);

    return (
        <div className="page-content">

            {statusMsg && <div className="alert-banner alert-success">{statusMsg}</div>}
            {errorMsg  && <div className="alert-banner alert-danger">{errorMsg}</div>}

            {/* ── Page Header ───────────────────────────────────────── */}
            <div className="page-header">
                <div>
                    <h2 className="page-title">
                        <CheckSquare size={24} style={{ color: 'var(--primary)' }} />
                        Validations Queue
                    </h2>
                    <p className="page-subtitle">Review and formally approve certificates generated by the administrator.</p>
                </div>
            </div>

            {/* ── Activity Selector ─────────────────────────────────── */}
            <div className="card" style={{ maxWidth: 480, marginBottom: 24 }}>
                <div className="form-group" style={{ marginBottom: 0 }}>
                    <label className="form-label" htmlFor="val-activity">Select Activity</label>
                    <select id="val-activity" className="form-control"
                        value={actId}
                        onChange={e => loadCerts(e.target.value)}
                    >
                        <option value="">— Choose an activity to review —</option>
                        {activities.map(a => (
                            <option key={a.id} value={a.id}>{a.act_name}</option>
                        ))}
                    </select>
                </div>
            </div>

            {/* ── Certificate List ──────────────────────────────────── */}
            {isLoading && <p style={{ color: 'var(--text-secondary)' }}>Loading certificate records…</p>}

            {!isLoading && actId && (
                <>
                    {certs.length === 0 ? (
                        <div className="card" style={{ padding: 32, textAlign: 'center', color: 'var(--text-secondary)' }}>
                            No certificates have been generated for this activity yet.<br />
                            Ask the administrator to run the certificate generation step first.
                        </div>
                    ) : (
                        <>
                            {/* Bulk action bar */}
                            <div style={{ display: 'flex', gap: 12, marginBottom: 20 }}>
                                {!allValidated && (
                                    <button className="btn btn-success" onClick={() => handleValidate(true)}>
                                        <Check size={16} aria-hidden="true" /> Approve All {certs.length} Certificate(s)
                                    </button>
                                )}
                                {allValidated && (
                                    <button className="btn btn-danger" onClick={() => handleValidate(false)}>
                                        <X size={16} aria-hidden="true" /> Revoke Approval
                                    </button>
                                )}
                            </div>

                            {/* Certificate records table */}
                            <div className="table-container">
                                <table className="data-table">
                                    <thead>
                                        <tr>
                                            <th>Certificate No.</th>
                                            <th>Type</th>
                                            <th>Participant Type</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {certs.map(c => (
                                            <tr key={c.part_id}>
                                                <td style={{ fontFamily: 'monospace', fontWeight: 600 }}>{c.certificate_no}</td>
                                                <td>{c.certificate_type}</td>
                                                <td style={{ textTransform: 'capitalize' }}>{c.part_type}</td>
                                                <td>
                                                    {c.cert_status === 2 ? (
                                                        <span className="badge badge-success">Validated</span>
                                                    ) : (
                                                        <span className="badge badge-warning">Pending</span>
                                                    )}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </>
                    )}
                </>
            )}
        </div>
    );
}
